title: Kaushik Ghosh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p style="font-size:13px"> <br>BE, Information Technology, School of Information Technology, West Bengal University of Technology<br>
  MBA, Vinod Gupta School of Management, Indian Institute of Technology, IIT Khragpur<br>
  Ph.D. Research Scholar, Indian Institute of Foreign Trade <br>
  Author | Independent Researcher | Senior Member, ACM | Oracle Cloud Certified Generative AI pro | Govt. Officer (Ministry of Defence, & Ministray of Jal Shakti, Govt. of India) | Asst. Professor (Visiting)<font> </p>
  <br> <a href="https://www.linkedin.com/in/kaushik-ghosh-bb3a2430/">View My LinkedIn Profile</a> <br> 
  <br> <a href="https://hq.ssrn.com/submissions/MyPapers.cfm?partid=4021364">View My SSRN Page</a> <br>
  <br> <a href="https://scholar.google.com/citations?user=k_4r9vQAAAAJ&hl=en">View My Google Scholar Page</a> <br> 
  <br> <a href="https://www.researchgate.net/profile/Kaushik-Ghosh-21">View My ResearchGate Page</a> <br> 
  <br> <a href="https://kaus2007.github.io/online-cv/">View My Website</a> <br> 
  <br> <a href="https://awards.acm.org/award-recipients/ghosh_8912100">View My ACM Page</a> <br> 
  <br> <a href="https://kaus2007.github.io/online-cv/">View My Website</a> <br> 
# theme: jekyll-theme-leap-day
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

theme: jekyll-theme-minimal
